### ISSUE TITLE
[Grading Req: Repository Quality 10%][Project Requirements] >> Have a clean repository that meets quality coding standards... 

### ISSUE THREAD

**Issue by SquirrelsAtARave** [ahermez/hybrid-tracker-project-1#45]
### ToDo list for this Issue:
- [x]  meets quality coding standards for file structure
- [x]  meets quality coding standards for naming conventions
- [x]  uses standard best practices for class/id naming conventions
- [x]  meets quality coding standards for indentation
- [x]  meets quality coding standards for quality comments

**Comment by SquirrelsAtARave** [comment]
ToDo list for this Issue: 

- [ ] meets quality coding standards for file structure
- [ ] meets quality coding standards for naming conventions
- [ ] meets quality coding standards for best practices for class/id naming conventions
- [ ] meets quality coding standards for indentation
- [ ] meets quality coding standards for quality comments

**Comment by SquirrelsAtARave** [comment]
### Programming 101: File Structures:
https://medium.com/@deshayk/programming-101-file-structures-2e4699ac0fc2

**Comment by SquirrelsAtARave** [comment]
### Naming Conventions: 
https://devopedia.org/naming-conventions#qst-ans-1

**Comment by SquirrelsAtARave** [comment]
### HTML ID and CLASS naming best practices
https://stackoverflow.com/questions/44748090/html-id-and-class-naming-best-practices

**Comment by SquirrelsAtARave** [comment]
### Best practices for writing code comments
https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/
